branch-defaults:
  docker:
    environment: openopps-platform-dev
    group_suffix: null
global:
  application_name: openopps-platform
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.06.2-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: openopps-builder
  repository: null
  sc: git
  workspace_type: Application
